name: GOONE

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-go@v5.4.0

    - name: Build
      run: "go build -v ./..."

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0

      - name: Test
        run: "go -v tests ./..."

  tests-race:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0

      - name: Test
        run: "go test -race -v ./..."

  lint:
    needs: [tests, tests-race]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0

      - name: Lint
        run: "golangci/golangci-lint-action@v6"